"""Phase 3: generate the mirrored loopback harness for a UoP.

The harness is the mirror image of the UoP's descriptor:

- every UoP *subscriber* connection becomes a harness *publisher*
  (``send_<CONN>`` helper),
- every UoP *publisher* connection becomes a harness *subscriber*
  (``recv_<CONN>`` helper).

The generated ``<uop>_harness`` binary spawns the UoP as a child process,
runs the ``drive`` USER CODE region (stimulus + verification, written by
the developer — the expected transform is application-specific and cannot
be invented), then SIGTERMs the child and requires a clean exit.

The default ``drive`` region fails loudly instead of silently passing,
so an unimplemented harness can never report a false PASS.
"""

from .util import member_stems, render_region as _region

_members = member_stems

__all__ = [
    "default_regions",
    "emit_harness_c",
    "emit_cmake_harness",
]

# UoP role -> harness role (direction and role both flip).
_MIRROR_DIRECTION = {
    "source": "FACE_TSS_DESTINATION",
    "destination": "FACE_TSS_SOURCE",
}
_MIRROR_ROLE = {
    "publisher": "FACE_TSS_ROLE_SUBSCRIBER",
    "subscriber": "FACE_TSS_ROLE_PUBLISHER",
}

# Fixed base port for the CTest loopback. Must be free at test time;
# override by editing the generated CMakeLists.
CTEST_BASE_PORT = 48601


def default_regions(model):
    sends = [f"send_{c.name}" for c in model.connections
             if c.role == "subscriber"]
    recvs = [f"recv_{c.name}" for c in model.connections
             if c.role == "publisher"]
    todo = ["/* TODO: drive the UoP under test.",
            " *",
            " * Stimulus + verification are application-specific, so this",
            " * region is yours to write. It survives regeneration.",
            " *"]
    if sends:
        todo.append(" * Send inputs with:")
        todo.extend(f" *   rc = {s}(tss, {s[5:].lower()}_id, &in);"
                    for s in sends)
    if recvs:
        todo.append(" * Receive replies with:")
        todo.extend(f" *   rc = {r}(tss, {r[5:].lower()}_id, &out);"
                    for r in recvs)
    todo.append(" * Check every expectation with CHECK(cond, fmt, ...).")
    todo.append(" */")
    todo.append('printf("FAIL: drive region not implemented\\n");')
    todo.append("failures++;")
    return {"drive": "\n".join(todo) + "\n"}


def emit_harness_c(model, regions):
    """Render ``<uop>_harness.c``. Returns (source, orphans)."""
    uop = model.name
    harness = f"{uop}_harness"
    members = _members(model)
    defaults = default_regions(model)
    used = set()

    def region(name, indent=""):
        used.add(name)
        body = regions.get(name, defaults[name])
        return _region(name, body, indent)

    # Harness publishers = UoP subscribers; harness subscribers = UoP publishers.
    h_pubs = [c for c in model.connections if c.role == "subscriber"]
    h_subs = [c for c in model.connections if c.role == "publisher"]

    L = []
    L.append("/*")
    L.append(f" * {harness}.c -- GENERATED by uop-scaffold. DO NOT EDIT by hand.")
    L.append(" *")
    L.append(" * Loopback rig for the UoP under test: this rig takes the mirror")
    L.append(" * image of the UoP's connections, spawns the UoP as a child,")
    L.append(" * drives its inputs, verifies its outputs, then SIGTERMs the")
    L.append(" * child and requires a clean exit.")
    L.append(" *")
    L.append(f" * Usage: {harness} <path_to_{uop}> <base_port>")
    L.append(" */")
    L.append("#define _POSIX_C_SOURCE 200809L /* kill(), fork(), waitpid() */")
    L.append("#include <stdint.h>")
    L.append("#include <stdio.h>")
    L.append("#include <stdlib.h>")
    L.append("#include <string.h>")
    L.append("#include <signal.h>")
    L.append("#include <unistd.h>")
    L.append("#include <sys/types.h>")
    L.append("#include <sys/wait.h>")
    L.append("")
    L.append("#include <face_tss/tss.h>")
    L.append("")
    L.append(f'#include "{uop}_types.h"')
    L.append("")
    L.append("#define IO_TIMEOUT_NS 5000000000LL /* 5 s */")
    L.append("#define MAX_MESSAGE_SIZE 65536")
    L.append("")
    L.append("static int failures = 0;")
    L.append("")
    L.append("#define CHECK(cond, ...)                                                 \\")
    L.append("    do {                                                                  \\")
    L.append("        if (!(cond)) {                                                    \\")
    L.append('            printf("FAIL: " __VA_ARGS__);                                 \\')
    L.append('            printf("\\n");                                                \\')
    L.append("            failures++;                                                   \\")
    L.append("        }                                                                 \\")
    L.append("    } while (0)")
    L.append("")
    L.append("#define CHECK_RC(call)                                                  \\")
    L.append("    do {                                                                \\")
    L.append("        FACE_TSS_RETURN_CODE rc_ = (call);                               \\")
    L.append("        if (rc_ != FACE_TSS_RC_NO_ERROR) {                               \\")
    L.append('            printf("FAIL: %s -> %s\\n", #call, face_tss_rc_str(rc_));    \\')
    L.append("            failures++;                                                 \\")
    L.append("        }                                                               \\")
    L.append("    } while (0)")
    L.append("")

    # send_/recv_ helpers ------------------------------------------------
    if h_pubs or h_subs:
        L.append("/* ------------------------------------------------------------------ */")
        L.append("/* Mirror-image transport helpers (non-static so -Wunused-function   */")
        L.append("/* stays quiet until the drive region calls them)                     */")
        L.append("/* ------------------------------------------------------------------ */")
    for c in h_pubs:
        t = model.type_by_name(c.type)
        stem = members[c.name]
        L.append(f"FACE_TSS_RETURN_CODE send_{c.name}(FACE_TSS *tss,")
        L.append(f"        FACE_TSS_CONNECTION_ID_TYPE conn, const {t.name}_t *msg)")
        L.append("{")
        L.append(f"    uint8_t wire[{t.name.upper()}_WIRE_SIZE];")
        L.append("    FACE_TSS_TRANSACTION_ID_TYPE txn ="
                 " FACE_TSS_TRANSACTION_ID_UNSPECIFIED;")
        L.append("")
        L.append(f"    {t.name}_encode(msg, wire);")
        L.append("    return face_tss_send_message(tss, conn, IO_TIMEOUT_NS, &txn,")
        L.append("                                 wire, sizeof(wire));")
        L.append("}")
        L.append("")
    for c in h_subs:
        t = model.type_by_name(c.type)
        L.append(f"FACE_TSS_RETURN_CODE recv_{c.name}(FACE_TSS *tss,")
        L.append(f"        FACE_TSS_CONNECTION_ID_TYPE conn, {t.name}_t *msg)")
        L.append("{")
        L.append("    FACE_TSS_MESSAGE m;")
        L.append("    FACE_TSS_TRANSACTION_ID_TYPE txn = 0;")
        L.append("    FACE_TSS_RETURN_CODE rc;")
        L.append("")
        L.append("    memset(&m, 0, sizeof(m));")
        L.append("    rc = face_tss_receive_message(tss, conn, IO_TIMEOUT_NS, 0,")
        L.append("                                  &txn, &m, NULL);")
        L.append("    if (rc != FACE_TSS_RC_NO_ERROR) {")
        L.append("        return rc;")
        L.append("    }")
        L.append(f"    rc = {t.name}_decode(m.payload, m.payload_len, msg)")
        L.append("        != 0 ? FACE_TSS_RC_INVALID_PARAM : FACE_TSS_RC_NO_ERROR;")
        L.append("    face_tss_message_fini(&m);")
        L.append("    return rc;")
        L.append("}")
        L.append("")

    # main ---------------------------------------------------------------
    L.append("int main(int argc, char **argv)")
    L.append("{")
    for c in model.connections:
        L.append(f"    char {members[c.name]}_addr[FACE_TSS_MAX_ADDRESS];")
    L.append("    char portstr[16];")
    L.append("    long base_port;")
    L.append("    FACE_TSS_CONFIG cfg;")
    L.append("    FACE_TSS *tss = NULL;")
    L.append("    FACE_TSS_CONNECTION_CONFIG cc;")
    for c in model.connections:
        L.append(f"    FACE_TSS_CONNECTION_ID_TYPE {members[c.name]}_id = 0;")
    L.append("    FACE_TSS_MESSAGE_SIZE_TYPE max_size;")
    L.append("    pid_t child;")
    L.append("")
    L.append("    if (argc != 3) {")
    L.append(f'        fprintf(stderr, "usage: %s <{uop}_bin> <base_port>\\n", argv[0]);')
    L.append("        return 2;")
    L.append("    }")
    max_base = 65535 - (len(model.connections) - 1)
    L.append("    if (sscanf(argv[2], \"%ld\", &base_port) != 1 || base_port <= 0 ||")
    L.append(f"        base_port > {max_base}) {{")
    L.append(f'        fprintf(stderr, "{harness}: invalid base port\\n");')
    L.append("        return 2;")
    L.append("    }")
    for i, c in enumerate(model.connections):
        stem = members[c.name]
        L.append(f"    snprintf({stem}_addr, sizeof({stem}_addr),")
        L.append(f'             "tcp://127.0.0.1:%ld", base_port + {i});')
    L.append('    snprintf(portstr, sizeof(portstr), "%ld", base_port);')
    L.append("")
    L.append("    /* Mirror image of the UoP's config: roles and directions flip. */")
    L.append(f'    face_tss_config_init(&cfg, "{harness}");')
    L.append("")
    for c in model.connections:
        stem = members[c.name]
        L.append("    memset(&cc, 0, sizeof(cc));")
        L.append(f'    strncpy(cc.name, "{c.name}", sizeof(cc.name) - 1);')
        L.append(f"    strncpy(cc.address, {stem}_addr, sizeof(cc.address) - 1);")
        L.append(f"    cc.direction = {_MIRROR_DIRECTION[c.direction]};")
        L.append("    cc.transport = FACE_TSS_TRANSPORT_PUBSUB;")
        L.append(f"    cc.role = {_MIRROR_ROLE[c.role]};")
        L.append("    cc.max_message_size = MAX_MESSAGE_SIZE;")
        L.append("    cc.queue_depth = 64;")
        L.append("    CHECK_RC(face_tss_config_add(&cfg, &cc));")
        L.append("")
    L.append(f'    tss = face_tss_create("{harness}");')
    L.append('    CHECK(tss != NULL, "face_tss_create returned NULL");')
    L.append("    if (tss) {")
    L.append("        CHECK_RC(face_tss_initialize(tss, &cfg));")
    for c in model.connections:
        stem = members[c.name]
        L.append(f"        CHECK_RC(face_tss_create_connection(tss, \"{c.name}\","
                 f" &{stem}_id,")
        L.append("                                            &max_size, 0));")
    L.append("    }")
    L.append("")
    L.append("    /* Spawn the UoP under test. */")
    L.append("    child = fork();")
    L.append("    if (child == 0) {")
    L.append("        execl(argv[1], argv[1], portstr, (char *)NULL);")
    L.append('        perror("execl");')
    L.append("        _exit(127);")
    L.append("    }")
    L.append('    CHECK(child > 0, "fork failed");')
    L.append("    sleep(1); /* let the UoP boot and its dials settle */")
    L.append("")
    L.append(region("drive"))
    L.append("")
    L.append("    /* Graceful shutdown: SIGTERM, then reap and check clean exit. */")
    L.append("    if (child > 0) {")
    L.append("        int status = 0;")
    L.append("        kill(child, SIGTERM);")
    L.append("        waitpid(child, &status, 0);")
    L.append('        CHECK(WIFEXITED(status) && WEXITSTATUS(status) == 0,')
    L.append('              "UoP did not exit cleanly (status=%d)", status);')
    L.append("    }")
    L.append("")
    L.append("    if (tss) {")
    for c in model.connections:
        stem = members[c.name]
        L.append(f"        face_tss_destroy_connection(tss, {stem}_id);")
    L.append("        face_tss_destroy(tss);")
    L.append("    }")
    L.append("    face_tss_config_fini(&cfg);")
    L.append("")
    L.append("    if (failures == 0) {")
    L.append(f'        printf("{uop}: LOOPBACK PASS\\n");')
    L.append("        return 0;")
    L.append("    }")
    L.append(f'    printf("{uop}: LOOPBACK FAIL (%d failures)\\n", failures);')
    L.append("    return 1;")
    L.append("}")
    L.append("")

    orphans = sorted(set(regions) - used - set(defaults))
    return "\n".join(L), orphans


def emit_cmake_harness(model):
    """CMake snippet: harness target + CTest loopback registration."""
    uop = model.name
    harness = f"{uop}_harness"
    return f"""\
add_executable({harness} {harness}.c)
target_include_directories({harness} PRIVATE "${{TSS_ROOT}}/c/include")
target_link_directories({harness} PRIVATE "${{TSS_ROOT}}/build")
target_link_libraries({harness} PRIVATE TSS)

enable_testing()
add_test(NAME {uop}_loopback
         COMMAND {harness} $<TARGET_FILE:{uop}> {CTEST_BASE_PORT})
"""
