"""Emit C99 type codecs for the descriptor's scalar message types.

Generates a single self-contained header ``<uop>_types.h``:

- ``typedef struct { ... } <type>_t;`` per message type
- ``<TYPE>_WIRE_SIZE`` constant per type
- ``<type>_encode(const <type>_t *m, uint8_t out[N])``
- ``<type>_decode(const uint8_t *in, size_t len, <type>_t *m)`` → 0 / -1

Wire format is packed little-endian, shift-based (no alignment or
host-endianness hazards). This is the zero-dependency path for scalar-only
models. Richer models (strings, nested tables, unions) are out of scope
here: the designed seam is a future ``schema: foo.fbs`` key on the type
that delegates to ``face_tss_codegen.py`` instead of this emitter.
"""

from .model import SCALAR_TYPES

__all__ = ["emit_types_header"]

_HEADER_PREAMBLE = """\
/* Generated by uop-scaffold. DO NOT EDIT - regenerate from the descriptor.
 * Packed little-endian codecs for this UoP's message types.
 */
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
"""


def _encode_lines(field, idx):
    """C statements storing field ``m->name`` at out[idx..]."""
    n = field.name
    kind = field.type
    L = []
    if kind == "bool":
        L.append(f"    out[{idx}] = (uint8_t)(m->{n} ? 1 : 0);")
    elif kind in ("int8", "uint8"):
        L.append(f"    out[{idx}] = (uint8_t)m->{n};")
    elif kind in ("int16", "uint16"):
        L.append(f"    out[{idx}] = (uint8_t)((uint16_t)m->{n} & 0xFFu);")
        L.append(f"    out[{idx + 1}] = (uint8_t)(((uint16_t)m->{n} >> 8) & 0xFFu);")
    elif kind in ("int32", "uint32", "float"):
        if kind == "float":
            L.append(f"    {{ uint32_t u_; memcpy(&u_, &m->{n}, 4);")
            v = "u_"
        else:
            v = f"(uint32_t)m->{n}"
        L.append(f"    out[{idx}] = (uint8_t)({v} & 0xFFu);")
        L.append(f"    out[{idx + 1}] = (uint8_t)(({v} >> 8) & 0xFFu);")
        L.append(f"    out[{idx + 2}] = (uint8_t)(({v} >> 16) & 0xFFu);")
        L.append(f"    out[{idx + 3}] = (uint8_t)(({v} >> 24) & 0xFFu);")
        if kind == "float":
            L.append("    }")
    elif kind in ("int64", "uint64", "double"):
        if kind == "double":
            L.append(f"    {{ uint64_t u_; memcpy(&u_, &m->{n}, 8);")
            v = "u_"
        else:
            v = f"(uint64_t)m->{n}"
        for b in range(8):
            L.append(f"    out[{idx + b}] = (uint8_t)(({v} >> {8 * b}) & 0xFFu);")
        if kind == "double":
            L.append("    }")
    else:  # pragma: no cover - validator rejects unknown types
        raise AssertionError(f"unknown scalar {kind}")
    return L


def _decode_lines(field, idx):
    """C statements loading ``m->name`` from in[idx..]."""
    n = field.name
    kind = field.type
    L = []
    if kind == "bool":
        L.append(f"    m->{n} = in[{idx}] != 0;")
    elif kind == "int8":
        L.append(f"    m->{n} = (int8_t)in[{idx}];")
    elif kind == "uint8":
        L.append(f"    m->{n} = in[{idx}];")
    elif kind in ("int16", "uint16"):
        c = "int16_t" if kind == "int16" else "uint16_t"
        L.append(f"    m->{n} = ({c})((uint16_t)in[{idx}] | "
                 f"((uint16_t)in[{idx + 1}] << 8));")
    elif kind in ("int32", "uint32", "float"):
        expr = (f"((uint32_t)in[{idx}] | ((uint32_t)in[{idx + 1}] << 8) | "
                f"((uint32_t)in[{idx + 2}] << 16) | "
                f"((uint32_t)in[{idx + 3}] << 24))")
        if kind == "float":
            L.append(f"    {{ uint32_t u_ = {expr}; memcpy(&m->{n}, &u_, 4); }}")
        else:
            c = "int32_t" if kind == "int32" else "uint32_t"
            L.append(f"    m->{n} = ({c}){expr};")
    elif kind in ("int64", "uint64", "double"):
        parts = " | ".join(
            f"((uint64_t)in[{idx + b}] << {8 * b})" for b in range(8))
        expr = f"({parts})"
        if kind == "double":
            L.append(f"    {{ uint64_t u_ = {expr}; memcpy(&m->{n}, &u_, 8); }}")
        else:
            c = "int64_t" if kind == "int64" else "uint64_t"
            L.append(f"    m->{n} = ({c}){expr};")
    else:  # pragma: no cover - validator rejects unknown types
        raise AssertionError(f"unknown scalar {kind}")
    return L


def emit_types_header(model):
    """Render the ``<uop>_types.h`` header for a validated UopModel."""
    guard = f"{model.name.upper()}_TYPES_H"
    out = [_HEADER_PREAMBLE.format(guard=guard)]
    for t in model.types:
        tname = f"{t.name}_t"
        macro = f"{t.name.upper()}_WIRE_SIZE"
        out.append(f"typedef struct {{")
        for f in t.fields:
            ctype, _ = SCALAR_TYPES[f.type]
            out.append(f"    {ctype} {f.name};")
        out.append(f"}} {tname};")
        out.append(f"#define {macro} {t.wire_size}")
        out.append("")
        out.append(f"static inline void {t.name}_encode(const {tname} *m, "
                   f"uint8_t out[{macro}]) {{")
        idx = 0
        for f in t.fields:
            out.extend(_encode_lines(f, idx))
            idx += f.wire_size
        out.append("}")
        out.append("")
        out.append(f"static inline int {t.name}_decode(const uint8_t *in, "
                   f"size_t len, {tname} *m) {{")
        out.append(f"    if (len != {macro}) {{ return -1; }}")
        idx = 0
        for f in t.fields:
            out.extend(_decode_lines(f, idx))
            idx += f.wire_size
        out.append("    return 0;")
        out.append("}")
        out.append("")
    out.append(f"#endif /* {guard} */")
    out.append("")
    return "\n".join(out)
