/* Typed Pub/Sub demo: publisher streams PositionReport structs, subscriber
 * prints decoded fields. Uses the FACE TypedTS interface with type support
 * generated by tools/face_tss_codegen.py from c/schemas/position_report.fbs.
 *   face_tss_typed_pubsub pub [config.json]
 *   face_tss_typed_pubsub sub [config.json]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(_WIN32)
#include <windows.h>
static void msleep(long ms) { Sleep((DWORD)ms); }
#else
#include <time.h>
static void msleep(long ms)
{
    struct timespec ts;
    ts.tv_sec = ms / 1000;
    ts.tv_nsec = (ms % 1000) * 1000000L;
    nanosleep(&ts, NULL);
}
#endif

#include "face_tss/config.h"
#include "face_tss/tss.h"
#include "face_tss/typed.h"
#include "positionreport_typed.h"

#define TYPE_NAME "FaceTSS.PositionReport"

static int run_pub(const char *cfg_path)
{
    FACE_TSS_CONFIG cfg;
    FACE_TSS *tss;
    FACE_TSS_CONNECTION_ID_TYPE id;
    FACE_TSS_MESSAGE_SIZE_TYPE mx;
    FACE_TSS_RETURN_CODE rc;
    int i;
    face_tss_config_init(&cfg, "demo");
    rc = face_tss_config_from_file(cfg_path, &cfg);
    if (rc != FACE_TSS_RC_NO_ERROR) {
        printf("[pub] config %s: %s\n", cfg_path, face_tss_rc_str(rc));
        return 1;
    }
    tss = face_tss_create("typed-publisher");
    rc = face_tss_initialize(tss, &cfg);
    printf("[pub] initialize -> %s\n", face_tss_rc_str(rc));
    rc = face_tss_typed_register(tss, &PositionReport_type_support);
    printf("[pub] typed_register -> %s\n", face_tss_rc_str(rc));
    rc = face_tss_create_connection(tss, "POSITION", &id, &mx, 0);
    printf("[pub] create POSITION -> %s id=%lld\n",
           face_tss_rc_str(rc), (long long)id);
    if (rc != FACE_TSS_RC_NO_ERROR)
        return 1;
    msleep(500);
    for (i = 1; i <= 20; i++) {
        PositionReport r;
        char vehicle[16];
        FACE_TSS_TRANSACTION_ID_TYPE txn =
            FACE_TSS_TRANSACTION_ID_UNSPECIFIED;
        snprintf(vehicle, sizeof(vehicle), "UAV-%d", i);
        memset(&r, 0, sizeof(r));
        r.vehicle_id = vehicle;
        r.latitude_deg = 42.28 + i * 0.001;
        r.longitude_deg = -83.74 - i * 0.001;
        r.altitude_m = 200.0f + (float)i;
        r.heading_deg = (float)(i * 18 % 360);
        r.valid = true;
        rc = face_tss_typed_send(tss, id, 5000000000LL, &txn, TYPE_NAME, &r);
        printf("[pub] sent %s txn=%lld -> %s\n", vehicle, (long long)txn,
               face_tss_rc_str(rc));
        msleep(200);
    }
    face_tss_destroy_connection(tss, id);
    face_tss_destroy(tss);
    face_tss_config_fini(&cfg);
    printf("[pub] done\n");
    return 0;
}

static int run_sub(const char *cfg_path)
{
    FACE_TSS_CONFIG cfg;
    FACE_TSS *tss;
    FACE_TSS_CONNECTION_ID_TYPE id;
    FACE_TSS_MESSAGE_SIZE_TYPE mx;
    FACE_TSS_RETURN_CODE rc;
    int i, received = 0;
    face_tss_config_init(&cfg, "demo");
    rc = face_tss_config_from_file(cfg_path, &cfg);
    if (rc != FACE_TSS_RC_NO_ERROR) {
        printf("[sub] config %s: %s\n", cfg_path, face_tss_rc_str(rc));
        return 1;
    }
    tss = face_tss_create("typed-subscriber");
    rc = face_tss_initialize(tss, &cfg);
    printf("[sub] initialize -> %s\n", face_tss_rc_str(rc));
    rc = face_tss_typed_register(tss, &PositionReport_type_support);
    printf("[sub] typed_register -> %s\n", face_tss_rc_str(rc));
    rc = face_tss_create_connection(tss, "POSITION", &id, &mx, 0);
    printf("[sub] create POSITION -> %s\n", face_tss_rc_str(rc));
    if (rc != FACE_TSS_RC_NO_ERROR)
        return 1;
    for (i = 0; i < 30; i++) {
        PositionReport r;
        FACE_TSS_TRANSACTION_ID_TYPE txn = 0;
        FACE_TSS_HEADER header;
        FACE_TSS_QOS_EVENT qos;
        memset(&r, 0, sizeof(r));
        rc = face_tss_typed_receive(tss, id, 500 * 1000000LL, 0, &txn,
                                    TYPE_NAME, &r, &header, &qos);
        if (rc == FACE_TSS_RC_TIMED_OUT)
            continue;
        if (rc != FACE_TSS_RC_NO_ERROR) {
            printf("[sub] receive -> %s\n", face_tss_rc_str(rc));
            break;
        }
        received++;
        printf("[sub] #%d txn=%lld %s lat=%.6f lon=%.6f alt=%.1f hdg=%.0f\n",
               received, (long long)txn, r.vehicle_id, r.latitude_deg,
               r.longitude_deg, r.altitude_m, r.heading_deg);
        PositionReport_fini(&r);
    }
    face_tss_destroy_connection(tss, id);
    face_tss_destroy(tss);
    face_tss_config_fini(&cfg);
    printf("[sub] done received=%d\n", received);
    return 0;
}

int main(int argc, char **argv)
{
    const char *mode, *cfg;
    if (argc < 2 || (strcmp(argv[1], "pub") && strcmp(argv[1], "sub"))) {
        printf("usage: %s [pub|sub] [config.json]\n", argv[0]);
        return 2;
    }
    mode = argv[1];
    if (argc > 2) {
        cfg = argv[2];
    } else if (!strcmp(mode, "pub")) {
        cfg = "configs/pubsub_publisher.json";
    } else {
        cfg = "configs/pubsub_subscriber.json";
    }
    return !strcmp(mode, "pub") ? run_pub(cfg) : run_sub(cfg);
}
