#!/usr/bin/env python3
"""face_tss_codegen.py - generate FACE TSS typed C wrappers from .fbs schemas.

Reads a FlatBuffers schema containing one flat table (scalar and string
fields only) and generates a C header + source implementing
FACE_TSS_TYPE_SUPPORT for that data type:

    python3 tools/face_tss_codegen.py c/schemas/position_report.fbs \\
        --out-dir c/generated

The generated codec uses the flatcc *runtime* builder API directly (the same
technique as c/src/envelope.c), so no flatcc compiler step is needed at build
time. The message GUID is a deterministic FNV-1a 64-bit hash of the qualified
type name, masked to a positive 63-bit value.

Supported field types: bool, byte/ubyte/int8/uint8, short/ushort/int16/uint16,
int/uint/int32/uint32, long/ulong/int64/uint64, float, double, string.
Unsupported (rejected with an error): nested tables, vectors, unions, enums,
explicit field `id` attributes, multiple tables per file.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

SCALARS = {
    # fbs type: (c type, width, kind)
    "bool": ("bool", 1, "u8"),
    "byte": ("int8_t", 1, "i8"),
    "int8": ("int8_t", 1, "i8"),
    "ubyte": ("uint8_t", 1, "u8"),
    "uint8": ("uint8_t", 1, "u8"),
    "short": ("int16_t", 2, "i16"),
    "int16": ("int16_t", 2, "i16"),
    "ushort": ("uint16_t", 2, "u16"),
    "uint16": ("uint16_t", 2, "u16"),
    "int": ("int32_t", 4, "i32"),
    "int32": ("int32_t", 4, "i32"),
    "uint": ("uint32_t", 4, "u32"),
    "uint32": ("uint32_t", 4, "u32"),
    "long": ("int64_t", 8, "i64"),
    "int64": ("int64_t", 8, "i64"),
    "ulong": ("uint64_t", 8, "u64"),
    "uint64": ("uint64_t", 8, "u64"),
    "float": ("float", 4, "f32"),
    "double": ("double", 8, "f64"),
}


def fnv1a64(s: str) -> int:
    h = 0xCBF29CE484222325
    for b in s.encode("utf-8"):
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def parse_fbs(path: Path):
    text = path.read_text()
    # strip // comments
    text = re.sub(r"//.*", "", text)
    ns_m = re.search(r"namespace\s+([\w.]+)\s*;", text)
    namespace = ns_m.group(1) if ns_m else ""
    tables = re.findall(r"table\s+(\w+)\s*\{([^}]*)\}", text)
    if not tables:
        raise ValueError(f"{path}: no table found")
    if len(tables) > 1:
        raise ValueError(f"{path}: multiple tables not supported")
    tname, body = tables[0]
    fields = []
    for m in re.finditer(r"(\w+)\s*:\s*([\w\[\]]+)\s*(?:=\s*[^;]+)?\s*;", body):
        fname, ftype = m.group(1), m.group(2)
        fields.append((fname, ftype))
    if not fields:
        raise ValueError(f"{path}: table {tname} has no fields")
    for fname, ftype in fields:
        if ftype == "string":
            continue
        if ftype in SCALARS:
            continue
        raise ValueError(
            f"{path}: field '{fname}' has unsupported type '{ftype}' "
            "(only scalars and string are supported)"
        )
    if re.search(r"\bid\s*:", body):
        raise ValueError(f"{path}: explicit field id attributes not supported")
    qname = f"{namespace}.{tname}" if namespace else tname
    return namespace, tname, qname, fields


def gen_header(tname, qname, fields, guid):
    guard = f"{tname.upper()}_TYPED_H"
    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("/* Generated by tools/face_tss_codegen.py - DO NOT EDIT. */")
    lines.append("")
    lines.append('#include "face_tss/typed.h"')
    lines.append("#include <stdbool.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append(f"/* FACE data type: {qname} (message GUID {guid}). */")
    lines.append(f"typedef struct {tname} {{")
    for fname, ftype in fields:
        if ftype == "string":
            lines.append(f"    char *{fname}; /* owned, freed by {tname}_fini */")
        else:
            ctype = SCALARS[ftype][0]
            lines.append(f"    {ctype} {fname};")
    lines.append(f"}} {tname};")
    lines.append("")
    lines.append(f"#define {tname.upper()}_MESSAGE_GUID "
                 f"((FACE_TSS_MESSAGE_GUID_TYPE){guid}LL)")
    lines.append("")
    lines.append(f"FACE_TSS_RETURN_CODE {tname}_serialize(")
    lines.append("    const void *msg, uint8_t **payload_out, size_t *payload_len_out);")
    lines.append(f"FACE_TSS_RETURN_CODE {tname}_deserialize(")
    lines.append("    const uint8_t *payload, size_t payload_len, void *msg_out);")
    lines.append(f"void {tname}_fini(void *msg);")
    lines.append("")
    lines.append(f"extern const FACE_TSS_TYPE_SUPPORT {tname}_type_support;")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    return "\n".join(lines) + "\n"


def gen_source(tname, qname, fields, guid):
    ctype_of = lambda ft: SCALARS[ft][0]
    width_of = lambda ft: SCALARS[ft][1]
    nfields = len(fields)
    L = []
    A = L.append
    A("/* Generated by tools/face_tss_codegen.py - DO NOT EDIT. */")
    A(f'/* Data type: {qname}. Codec over the flatcc runtime builder API,')
    A(" * mirroring c/src/envelope.c (no generated flatcc code needed). */")
    A("")
    A(f'#include "{tname.lower()}_typed.h"')
    A("")
    A("#include <stdlib.h>")
    A("#include <string.h>")
    A("")
    A("#include <flatcc/flatcc_builder.h>")
    A("#include <flatcc/flatcc_endian.h>")
    A("")
    # ---- serialize ----
    A(f"FACE_TSS_RETURN_CODE {tname}_serialize(")
    A("    const void *msg, uint8_t **payload_out, size_t *payload_len_out)")
    A("{")
    A(f"    const struct {tname} *m = (const struct {tname} *)msg;")
    A("    flatcc_builder_t builder;")
    A("    flatcc_builder_t *B = &builder;")
    A("    flatcc_builder_ref_t root;")
    str_fields = [f for f in fields if f[1] == "string"]
    for fname, _ in str_fields:
        A(f"    flatcc_builder_ref_t {fname}_ref = 0;")
    A("    void *buf;")
    A("    size_t size;")
    A("    if (!msg || !payload_out || !payload_len_out)")
    A("        return FACE_TSS_RC_INVALID_PARAM;")
    A("    flatcc_builder_init(B);")
    for fname, _ in str_fields:
        A(f"    {fname}_ref = flatcc_builder_create_string_str(")
        A(f"        B, m->{fname} ? m->{fname} : \"\");")
        A(f"    if (!{fname}_ref) {{ flatcc_builder_clear(B);")
        A("        return FACE_TSS_RC_NOT_AVAILABLE; }")
    A(f"    if (flatcc_builder_start_table(B, {nfields})) {{")
    A("        flatcc_builder_clear(B);")
    A("        return FACE_TSS_RC_NOT_AVAILABLE; }")
    for i, (fname, ftype) in enumerate(fields):
        if ftype == "string":
            A(f"    {{ flatcc_builder_ref_t *pref =")
            A(f"          flatcc_builder_table_add_offset(B, {i});")
            A("      if (!pref) { flatcc_builder_clear(B);")
            A("          return FACE_TSS_RC_NOT_AVAILABLE; }")
            A(f"      *pref = {fname}_ref; }}")
        else:
            ctype, width, _ = SCALARS[ftype]
            A(f"    {{ {ctype} *slot = ({ctype} *)")
            A(f"          flatcc_builder_table_add(B, {i}, {width}, {width});")
            A("      if (!slot) { flatcc_builder_clear(B);")
            A("          return FACE_TSS_RC_NOT_AVAILABLE; }")
            # write native-endian then convert, like envelope.c
            if width == 1:
                A(f"      *slot = m->{fname}; }}")
            elif width == 2:
                A(f"      uint16_t v16; memcpy(&v16, &m->{fname}, 2);")
                A("      flatbuffers_uint16_write_to_pe((uint16_t *)slot, v16); }")
            elif width == 4 and ftype == "float":
                A(f"      uint32_t v32; memcpy(&v32, &m->{fname}, 4);")
                A("      flatbuffers_uint32_write_to_pe((uint32_t *)slot, v32); }")
            elif width == 4:
                A(f"      uint32_t v32; memcpy(&v32, &m->{fname}, 4);")
                if ctype.startswith("int"):
                    A("      flatbuffers_int32_write_to_pe((int32_t *)slot, (int32_t)v32); }")
                else:
                    A("      flatbuffers_uint32_write_to_pe((uint32_t *)slot, v32); }")
            else:  # width == 8
                A(f"      uint64_t v64; memcpy(&v64, &m->{fname}, 8);")
                if ftype == "double":
                    A("      flatbuffers_uint64_write_to_pe((uint64_t *)slot, v64); }")
                elif ctype.startswith("int"):
                    A("      flatbuffers_int64_write_to_pe((int64_t *)slot, (int64_t)v64); }")
                else:
                    A("      flatbuffers_uint64_write_to_pe((uint64_t *)slot, v64); }")
    A("    root = flatcc_builder_end_table(B);")
    A("    if (!root || flatcc_builder_start_buffer(B, 0, 0, 0) ||")
    A("        !flatcc_builder_end_buffer(B, root)) {")
    A("        flatcc_builder_clear(B);")
    A("        return FACE_TSS_RC_NOT_AVAILABLE; }")
    A("    buf = flatcc_builder_finalize_buffer(B, &size);")
    A("    flatcc_builder_clear(B);")
    A("    if (!buf || size == 0) {")
    A("        if (buf) flatcc_builder_free(buf);")
    A("        return FACE_TSS_RC_NOT_AVAILABLE; }")
    A("    /* Copy to caller-owned malloc buffer: the finalize buffer must be")
    A("     * released with flatcc_builder_free, so keep ownership explicit. */")
    A("    {")
    A("        uint8_t *copy = (uint8_t *)malloc(size);")
    A("        if (!copy) { flatcc_builder_free(buf);")
    A("            return FACE_TSS_RC_NOT_AVAILABLE; }")
    A("        memcpy(copy, buf, size);")
    A("        flatcc_builder_free(buf);")
    A("        *payload_out = copy;")
    A("    }")
    A("    *payload_len_out = size;")
    A("    return FACE_TSS_RC_NO_ERROR;")
    A("}")
    A("")
    # ---- decode helpers ----
    A("/* Little-endian field readers (same approach as c/src/envelope.c). */")
    A("static uint16_t rd_u16(const uint8_t *p)")
    A("{ uint16_t v; memcpy(&v, p, 2); return v; }")
    A("static uint32_t rd_u32(const uint8_t *p)")
    A("{ uint32_t v; memcpy(&v, p, 4); return v; }")
    A("")
    # ---- deserialize ----
    A(f"FACE_TSS_RETURN_CODE {tname}_deserialize(")
    A("    const uint8_t *payload, size_t payload_len, void *msg_out)")
    A("{")
    A(f"    struct {tname} *m = (struct {tname} *)msg_out;")
    A("    const uint8_t *buf = payload;")
    A("    size_t len = payload_len;")
    A("    uint32_t root, table, vtable, vsize, tsize, entry, at, off, n, start;")
    A("    int32_t soff;")
    A("    uint8_t *copy = NULL;")
    A("    if (!msg_out)")
    A("        return FACE_TSS_RC_INVALID_PARAM;")
    A("    memset(m, 0, sizeof(*m));")
    A("    if (!buf || len == 0)")
    A("        return FACE_TSS_RC_INVALID_PARAM;")
    A("    if (((uintptr_t)buf & 3u) != 0u) {")
    A("        copy = (uint8_t *)malloc(len);")
    A("        if (!copy) return FACE_TSS_RC_NOT_AVAILABLE;")
    A("        memcpy(copy, buf, len); buf = copy;")
    A("    }")
    A("    if (len < 8 || len > (size_t)0xFFFFFFF0UL)")
    A("        { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
    A("    root = rd_u32(buf);")
    A("    if (root < 4 || root > (uint32_t)(len - 4))")
    A("        { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
    A("    table = root;")
    A("    soff = (int32_t)rd_u32(buf + table);")
    A("    vtable = table - (uint32_t)soff;")
    A("    if (vtable > (uint32_t)(len - 4))")
    A("        { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
    A("    vsize = rd_u16(buf + vtable);")
    A("    tsize = rd_u16(buf + vtable + 2);")
    A("    if (vsize < 4 || (vsize & 1u) || vsize > (uint32_t)(len - vtable) ||")
    A("        tsize < 4 || tsize > (uint32_t)(len - table))")
    A("        { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
    for i, (fname, ftype) in enumerate(fields):
        A(f"    /* field {i}: {fname} */")
        A("    entry = 0;")
        A(f"    if (vsize >= (uint32_t)(4 + 2 * {i} + 2))")
        A(f"        entry = rd_u16(buf + vtable + 4 + 2 * {i});")
        A("    if (entry != 0) {")
        if ftype == "string":
            A("        if (entry + 4 > tsize)")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A("        at = table + entry;")
            A("        if (at > (uint32_t)(len - 4))")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A("        off = rd_u32(buf + at);")
            A("        if (off == 0 || off > (uint32_t)(len - at - 4))")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A("        at += off;")
            A("        if (at > (uint32_t)(len - 4))")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A("        n = rd_u32(buf + at); start = at + 4;")
            A("        if (n + 1 > len - start || buf[start + n] != '\\0')")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A(f"        m->{fname} = (char *)malloc(n + 1);")
            A("        if (!m->%s) { free(copy); %s_fini(m);"
               % (fname, tname))
            A("            return FACE_TSS_RC_NOT_AVAILABLE; }")
            A(f"        memcpy(m->{fname}, buf + start, n);")
            A(f"        m->{fname}[n] = '\\0';")
        else:
            ctype, width, _ = SCALARS[ftype]
            A(f"        if (entry + {width} > tsize)")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A("        at = table + entry;")
            A(f"        if (at > (uint32_t)(len - {width}))")
            A("            { free(copy); return FACE_TSS_RC_INVALID_PARAM; }")
            A(f"        memcpy(&m->{fname}, buf + at, {width});")
        A("    }")
    A("    free(copy);")
    A("    return FACE_TSS_RC_NO_ERROR;")
    A("}")
    A("")
    # ---- fini ----
    A(f"void {tname}_fini(void *msg)")
    A("{")
    A(f"    struct {tname} *m = (struct {tname} *)msg;")
    A("    if (!m) return;")
    for fname, ftype in fields:
        if ftype == "string":
            A(f"    free(m->{fname}); m->{fname} = NULL;")
    A("}")
    A("")
    # ---- descriptor ----
    A(f"const FACE_TSS_TYPE_SUPPORT {tname}_type_support = {{")
    A(f"    {tname.upper()}_MESSAGE_GUID,")
    A(f'    "{qname}",')
    A(f"    {tname}_serialize,")
    A(f"    {tname}_deserialize,")
    A(f"    {tname}_fini,")
    A(f"    sizeof(struct {tname}),")
    A(f"    65536, /* max_size */")
    A("};")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate FACE TSS typed C wrapper from .fbs")
    ap.add_argument("schema", help="Input .fbs file")
    ap.add_argument("--out-dir", required=True, help="Output directory for generated files")
    args = ap.parse_args()
    schema = Path(args.schema)
    out_dir = Path(args.out_dir)
    namespace, tname, qname, fields = parse_fbs(schema)
    guid = fnv1a64(qname) & 0x7FFFFFFFFFFFFFFF
    if guid == 0:
        guid = 1
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = tname.lower()
    (out_dir / f"{stem}_typed.h").write_text(gen_header(tname, qname, fields, guid))
    (out_dir / f"{stem}_typed.c").write_text(gen_source(tname, qname, fields, guid))
    print(f"generated {stem}_typed.h / {stem}_typed.c for {qname} (guid {guid})")


if __name__ == "__main__":
    main()
